##################################################################################
# Cloudify Fabric built in types and plugins definitions.
##################################################################################
plugins:
    fabric:
        executor: central_deployment_agent
        source: https://github.com/GigaSpaces-ProfessionalServices/cloudify-fabric-plugin/archive/1.3.1-b0.zip
        package_name: cloudify-fabric-plugin
        package_version: '1.3.1.post1'
